security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        payment_hub_push:
            pattern: ^/subscriptions/http-push/retrieve
            provider:  chain_provider
            anonymous: true
        subscription_customer_data:
            pattern: ^/subscriptions/[0-9]+/customer_data
            provider:  chain_provider
            anonymous: true
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false