security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        payment_hub_push:
            pattern: ^/subscriptions/http-push/retrieve
            provider:  chain_provider
            anonymous: true
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
    access_control:
        - { path: ^/subscriptions/http-push/retrieve, role: IS_AUTHENTICATED_ANONYMOUSLY }