services:
    subscriptions.subscription_manager.api:
        class: Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - PHPaymentHubBundle\Entity\Subscription
            - "@doctrine.orm.entity_manager"

    ph_payment_hub.service.subscription:
        class: PH\PaymentHubBundle\Service\SubscriptionService
        arguments:
            - "@oro_email.mailer.processor"
            - "@oro_email.email_renderer"
            - "@doctrine.orm.entity_manager"