parameters:
    oro_address.address.entity.class: PH\PaymentHubBundle\Entity\Address
    oro_address.form.type.address.class: PH\PaymentHubBundle\Form\Type\AddressType

services:
    ph_payment_hub.service.subscription:
        class: PH\PaymentHubBundle\Service\SubscriptionService
        arguments:
            - "@oro_email.mailer.processor"
            - "@oro_email.email_renderer"
            - "@doctrine.orm.entity_manager"
            - "%from_email%"

    subscriptions.subscription_manager.api:
        class: Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - PH\PaymentHubBundle\Entity\Subscription
            - "@doctrine.orm.entity_manager"

    subscriptions.customer_manager.api:
        class: Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - PH\PaymentHubBundle\Entity\Customer
            - "@doctrine.orm.entity_manager"

    ph_payment_hub.listener.comment_task:
        class: PH\PaymentHubBundle\EventListener\CreateTaskForCommentListener
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@oro_activity.manager"
            - "@translator"
        tags:
            - { name: kernel.event_listener, event: payment_hub.customer.updated, method: onUpdate }