parameters:
    oro_address.address.entity.class: PH\PaymentHubBundle\Entity\Address
    oro_address.form.type.address.class: PH\PaymentHubBundle\Form\Type\AddressType

services:
    ph_payment_hub.service.subscription:
        class: PH\PaymentHubBundle\Service\SubscriptionService
        arguments:
            - "@oro_email.mailer.processor"
            - "@oro_email.email_renderer"
            - "@doctrine.orm.entity_manager"

    subscriptions.subscription_manager.api:
        class: Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - PH\PaymentHubBundle\Entity\Subscription
            - "@doctrine.orm.entity_manager"

    subscriptions.customer_manager.api:
        class: Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - PH\PaymentHubBundle\Entity\Customer
            - "@doctrine.orm.entity_manager"