PH\PaymentHubBundle\Entity\Subscription:
    properties:
        interval:
            - NotBlank: ~
        total:
            - NotBlank: ~
        startDate:
            - NotBlank: ~

PH\PaymentHubBundle\Entity\Payment:
    properties:
        iban:
            - Iban: ~
        bin:
            - Bic:
                message: This is not a valid Bank Identification Number (BIN).
