datagrids:
    ph-customers-grid:
        source:
            acl_resource: subscriptions.customer_view
            type: orm
            query:
                select:
                    - c.id
                    - c.namePrefix
                    - c.firstName
                    - c.createdAt
                    - c.updatedAt
                    - c.middleName
                    - c.lastName
                    - c.nameSuffix
                    - c.gender
                    - c.birthday
                    - c.email
                from:
                    - { table: PHPaymentHubBundle:Customer, alias: c }
        columns:
            id:
                label: 'Customer Id'
                frontend_type: integer
            firstName:
                label: 'First name'
                frontend_type: string
            lastName:
                label: 'Last name'
                frontend_type: string
            gender:
                label: 'Gender'
                frontend_type: string
            email:
                label: 'Email'
                frontend_type: string
            birthday:
                label: 'Birthday'
                frontend_type: datetime
            createdAt:
                label: 'Created'
                frontend_type: datetime
            updatedAt:
                label: 'Updated'
                frontend_type: datetime

        properties:
            id: ~
            update_link:
                type: url
                route: subscriptions.customer_update
                params:
                    - id
            view_link:
                type: url
                route: subscriptions.customer_view
                params:
                    - id
            delete_link:
                type: url
                route: ph_customers_api_delete_customer
                params:
                    - id
        sorters:
            columns:
                birthday:
                    data_name: c.birthday
                createdAt:
                    data_name: c.createdAt
                updatedAt:
                    data_name: c.createdAt
            default:
                createdAt: DESC
        filters:
            columns:
                firstName:
                    type: string
                    data_name: c.firstName
                lastName:
                    type: string
                    data_name: c.lastName
                email:
                    type: string
                    data_name: c.email
                createdAt:
                    type: datetime
                    data_name: c.createdAt
        actions:
            view:
                type:          navigate
                label:         View
                link:          view_link
                icon:          eye
                acl_resource:  subscriptions.customer_view
                rowAction:     true
            update:
                type:          navigate
                label:         Update
                link:          update_link
                icon:          edit
                acl_resource:  subscriptions.customer_update
            delete:
                type:          delete
                label:         Delete
                link:          delete_link
                icon:          trash
                acl_resource:  ph_customers_api_delete_customer

    ph-subscriptions-grid:
        source:
            acl_resource: subscriptions.subscription_view
            type: orm
            query:
                select:
                    - subscription.id
                    - subscription.orderId
                    - subscription.state
                    - subscription.createdAt
                    - subscription.updatedAt
                    - subscription.purchaseState
                    - subscription.paymentState
                    - subscription.checkoutCompletedAt
                    - subscription.total
                    - subscription.providerType
                    - GROUP_CONCAT(customer.firstName, ' ', customer.lastName) AS customerFullNames
                from:
                    - { table: PHPaymentHubBundle:Subscription, alias: subscription }
                join:
                    left:
                        - { join: subscription.customer, alias: customer }
        columns:
            orderId:
                label: 'Order Id'
                frontend_type: string
            total:
                label: 'Total ammount'
                frontend_type: string
            state:
                label: 'Subscription state'
                frontend_type: string
            purchaseState:
                label: 'Purchase State'
                frontend_type: string
            paymentState:
                label: 'Payment state'
                frontend_type: string
            checkoutCompletedAt:
                label: 'Purchase Completed'
                frontend_type: datetime
            providerType:
                label: 'Provider'
                fontend_type: string
            customerFullNames:
                label: 'Customer'
                fontend_type: string
            createdAt:
                label: 'Created'
                frontend_type: datetime
            updatedAt:
                label: 'Updated'
                frontend_type: datetime

        properties:
            id: ~
            update_link:
                type: url
                route: subscriptions.subscription_update
                params:
                    - id
            view_link:
                type: url
                route: subscriptions.subscription_view
                params:
                    - id
            delete_link:
                type: url
                route: subscriptions_api_delete_subscription
                params:
                    - id
            change_link:
                type: url
                route: subscriptions.subscription_change
                params:
                    - id
        sorters:
            columns:
                state:
                    data_name: subscription.state
                createdAt:
                    data_name: subscription.createdAt
                updatedAt:
                    data_name: subscription.createdAt
                providerType:
                    data_name: subscription.providerType
            default:
                state: ASC
        filters:
            columns:
                state:
                    type: string
                    data_name: subscription.state
                createdAt:
                    type: datetime
                    data_name: subscription.createdAt
        actions:
            view:
                type:          navigate
                label:         View
                link:          view_link
                icon:          eye
                acl_resource:  subscriptions.subscription_view
                rowAction:     true
            update:
                type:          navigate
                label:         Update
                link:          update_link
                icon:          edit
                acl_resource:  subscriptions.subscription_update
            delete:
                type:          delete
                label:         Delete
                link:          delete_link
                icon:          trash
                acl_resource:  subscriptions.subscription_delete
            change:
                type:          navigate
                label:         Change bank details
                link:          change_link
                icon:          university
                acl_resource:  subscriptions.subscription_change

    ph-customer-subscriptions-grid:
        source:
            acl_resource: subscriptions.subscription_view
            type: orm
            query:
                select:
                    - subscription.id
                    - subscription.orderId
                    - subscription.state
                    - subscription.createdAt
                    - subscription.updatedAt
                    - subscription.purchaseState
                    - subscription.paymentState
                    - subscription.checkoutCompletedAt
                    - subscription.total
                    - subscription.providerType
                from:
                    - { table: PHPaymentHubBundle:Subscription, alias: subscription }
                where:
                    and:
                        - subscription.customer = :customer
                join:
                    left:
                        - { join: subscription.customer, alias: customer }
            bind_parameters:
                customer:
                    path: customer
                    default: null
                    type: integer
        columns:
            orderId:
                label: 'Order Id'
                frontend_type: string
            total:
                label: 'Total ammount'
                frontend_type: string
            state:
                label: 'Order state'
                frontend_type: string
            purchaseState:
                label: 'Purchase State'
                frontend_type: string
            paymentState:
                label: 'Payment state'
                frontend_type: string
            checkoutCompletedAt:
                label: 'Purchase Completed'
                frontend_type: datetime
            providerType:
                label: 'Provider'
                fontend_type: string
            createdAt:
                label: 'Created'
                frontend_type: datetime
            updatedAt:
                label: 'Updated'
                frontend_type: datetime

        properties:
            id: ~
            update_link:
                type: url
                route: subscriptions.subscription_update
                params:
                    - id
            view_link:
                type: url
                route: subscriptions.subscription_view
                params:
                    - id
            delete_link:
                type: url
                route: subscriptions_api_delete_subscription
                params:
                    - id
        sorters:
            columns:
                state:
                    data_name: subscription.state
                createdAt:
                    data_name: subscription.createdAt
                updatedAt:
                    data_name: subscription.createdAt
                providerType:
                    data_name: subscription.providerType
            default:
                state: ASC
        filters:
            columns:
                state:
                    type: string
                    data_name: subscription.state
                createdAt:
                    type: datetime
                    data_name: subscription.createdAt
        actions:
            view:
                type:          navigate
                label:         View
                link:          view_link
                icon:          open
                acl_resource:  subscriptions.subscription_view
                rowAction:     true
            update:
                type:          navigate
                label:         Update
                link:          update_link
                icon:          edit
                acl_resource:  subscriptions.subscription_update
            delete:
                type:          delete
                label:         Delete
                link:          delete_link
                icon:          trash
                acl_resource:  subscriptions.subscription_delete


    ph-customer-notifications-grid:
        source:
            type: orm
            query:
                select:
                    - n.id
                    - n.type
                    - GROUP_CONCAT(customer.firstName, ' ', customer.lastName) AS customerFullName
                    - subscription.id AS subscriptionId
                    - n.sendAt
                from:
                    - { table: PHPaymentHubBundle:NotificationLog, alias: n }
                where:
                    and:
                        - n.customer = :customer
                join:
                    left:
                        - { join: n.customer, alias: customer }
                        - { join: n.subscription, alias: subscription }
            bind_parameters:
                customer:
                    path: customer
                    default: null
                    type: integer
        columns:
            id:
                label: 'Notification id'
                frontend_type: integer
            type:
                label: 'Notification type'
                frontend_type: string
            customerFullName:
                label: 'Customer'
            subscriptionId:
                label: 'Subscription id'
            sendAt:
                label: 'Created'
                frontend_type: datetime


        properties:
            id: ~
        sorters:
            columns:
                sendAt:
                    data_name: n.sendAt
            default:
                sendAt: DESC
