datagrids:
    ph-customers-grid:
        source:
            acl_resource: subscriptions.customer_view
            type: orm
            query:
                select:
                    - c.id
                    - c.namePrefix
                    - c.firstName
                    - c.createdAt
                    - c.updatedAt
                    - c.middleName
                    - c.lastName
                    - c.nameSuffix
                    - c.newsletterAllowed
                    - c.contactForbidden
                    - c.email
                    - COUNT(s.id) AS customerSubscriptions
                join:
                    left:
                        - { join: PHPaymentHubBundle:Subscription, alias: s, conditionType: WITH, condition: "c.id = s.customer" }
                from:
                    - { table: PHPaymentHubBundle:Customer, alias: c }
        columns:
            id:
                label: 'Customer Id'
                frontend_type: integer
            firstName:
                label: 'First name'
                frontend_type: string
            lastName:
                label: 'Last name'
                frontend_type: string
            email:
                label: 'Email'
                frontend_type: string
            customerSubscriptions:
                label: 'Subscriptions number'
                frontend_type: integer
            newsletterAllowed:
                label: 'Newsletter allowed'
                frontend_type: boolean
            contactForbidden:
                label: 'Contact is forbidden'
                frontend_type: boolean
            createdAt:
                label: 'Created'
                frontend_type: datetime
            updatedAt:
                label: 'Updated'
                frontend_type: datetime

        properties:
            id: ~
            update_link:
                type: url
                route: subscriptions.customer_update
                params:
                    - id
            view_link:
                type: url
                route: subscriptions.customer_view
                params:
                    - id
            delete_link:
                type: url
                route: ph_customers_api_delete_customer
                params:
                    - id
        sorters:
            columns:
                id:
                    data_name: c.id
                firstName:
                    data_name: c.firstName
                lastName:
                    data_name: c.lastName
                email:
                    data_name: c.email
                newsletterAllowed:
                    data_name: c.newsletterAllowed
                contactForbidden:
                    data_name: c.contactForbidden
                createdAt:
                    data_name: c.createdAt
                updatedAt:
                    data_name: c.createdAt
            default:
                createdAt: DESC
        filters:
            columns:
                id:
                    type: string
                    data_name: c.id
                firstName:
                    type: string
                    data_name: c.firstName
                lastName:
                    type: string
                    data_name: c.lastName
                email:
                    type: string
                    data_name: c.email
                newsletterAllowed:
                    type: boolean
                    data_name: c.newsletterAllowed
                contactForbidden:
                    type: boolean
                    data_name: c.contactForbidden
                createdAt:
                    type: datetime
                    data_name: c.createdAt
                updatedAt:
                    type: datetime
                    data_name: c.createdAt
        actions:
            view:
                type:          navigate
                label:         View
                link:          view_link
                icon:          eye
                acl_resource:  subscriptions.customer_view
                rowAction:     true
            update:
                type:          navigate
                label:         Update
                link:          update_link
                icon:          edit
                acl_resource:  subscriptions.customer_update
            delete:
                type:          delete
                label:         Delete
                link:          delete_link
                icon:          trash
                acl_resource:  ph_customers_api_delete_customer
        options:
            entityHint: subscriptions
            export: true

    ph-subscriptions-grid:
        source:
            acl_resource: subscriptions.subscription_view
            type: orm
            query:
                select:
                    - subscription.id
                    - subscription.orderId
                    - subscription.state
                    - subscription.createdAt
                    - subscription.updatedAt
                    - subscription.paymentState
                    - subscription.total
                    - subscription.total / 100 AS decimalTotal
                    - subscription.type
                    - subscription.providerType
                    - GROUP_CONCAT(customer.firstName, ' ', customer.lastName) AS customerFullNames
                    - subscription.source
                    - subscription.intention
                    - subscription.endDate
                from:
                    - { table: PHPaymentHubBundle:Subscription, alias: subscription }
                join:
                    left:
                        - { join: subscription.customer, alias: customer }
        columns:
            orderId:
                label: 'ph.paymenthub.subscriptions.label.id'
                frontend_type: string
            decimalTotal:
                label: 'Total amount'
                label: 'ph.paymenthub.subscriptions.label.amount'
                frontend_type: string
            state:
                label: 'ph.paymenthub.subscriptions.label.state'
                frontend_type: string
            paymentState:
                label: 'ph.paymenthub.subscriptions.label.payment_state'
                frontend_type: string
            providerType:
                label: 'ph.paymenthub.subscriptions.label.method'
                frontend_type: string
            source:
                label: 'ph.paymenthub.subscriptions.label.source'
                frontend_type: string
            intention:
                label: 'ph.paymenthub.subscriptions.label.intention'
                frontend_type: string
            type:
                label: 'ph.paymenthub.subscriptions.label.type'
                frontend_type: string
            customerFullNames:
                label: 'ph.paymenthub.subscriptions.label.customer'
                frontend_type: string
            endDate:
                label: 'ph.paymenthub.subscriptions.label.end_date'
                frontend_type: date
            createdAt:
                label: 'ph.paymenthub.subscriptions.label.created_at'
                frontend_type: datetime
            updatedAt:
                label: 'ph.paymenthub.subscriptions.label.updated_at'
                frontend_type: datetime

        properties:
            id: ~
            update_link:
                type: url
                route: subscriptions.subscription_update
                params:
                    - id
            view_link:
                type: url
                route: subscriptions.subscription_view
                params:
                    - id
            delete_link:
                type: url
                route: subscriptions_api_delete_subscription
                params:
                    - id
            change_link:
                type: url
                route: subscriptions.subscription_change
                params:
                    - id
        sorters:
            columns:
                orderId:
                    data_name: subscription.orderId
                decimalTotal:
                    data_name: subscription.total
                state:
                    data_name: subscription.state
                paymentState:
                    data_name: subscription.paymentState
                providerType:
                    data_name: subscription.providerType
                source:
                    data_name: subscription.source
                intention:
                    data_name: subscription.intention
                type:
                    data_name: subscription.type
                createdAt:
                    data_name: subscription.createdAt
                updatedAt:
                    data_name: subscription.createdAt
            default:
                state: ASC
        filters:
            columns:
                orderId:
                    type: string
                    data_name: subscription.orderId
                total:
                    type: string
                    data_name: subscription.total
                paymentState:
                    type: string
                    data_name: subscription.paymentState
                providerType:
                    type: string
                    data_name: subscription.providerType
                source:
                    type: string
                    data_name: subscription.source
                intention:
                    type: string
                    data_name: subscription.intention
                type:
                    type: string
                    data_name: subscription.type
                state:
                    type: string
                    data_name: subscription.state
                createdAt:
                    type: datetime
                    data_name: subscription.createdAt
                updatedAt:
                    type: datetime
                    data_name: subscription.updatedAt
        actions:
            view:
                type:          navigate
                label:         View
                link:          view_link
                icon:          eye
                acl_resource:  subscriptions.subscription_view
                rowAction:     true
            update:
                type:          navigate
                label:         Update
                link:          update_link
                icon:          edit
                acl_resource:  subscriptions.subscription_update
            delete:
                type:          delete
                label:         Delete
                link:          delete_link
                icon:          trash
                acl_resource:  subscriptions.subscription_delete
            change:
                type:          navigate
                label:         Change bank details
                link:          change_link
                icon:          university
                acl_resource:  subscriptions.subscription_change
        options:
            entityHint: subscriptions
            export: true

    ph-customer-subscriptions-grid:
        source:
            acl_resource: subscriptions.subscription_view
            type: orm
            query:
                select:
                    - subscription.id
                    - subscription.orderId
                    - subscription.state
                    - subscription.createdAt
                    - subscription.updatedAt
                    - subscription.purchaseState
                    - subscription.paymentState
                    - subscription.checkoutCompletedAt
                    - subscription.total
                    - subscription.type
                    - subscription.providerType
                    - subscription.source
                    - subscription.intention
                    - subscription.endDate
                from:
                    - { table: PHPaymentHubBundle:Subscription, alias: subscription }
                where:
                    and:
                        - subscription.customer = :customer
                join:
                    left:
                        - { join: subscription.customer, alias: customer }
            bind_parameters:
                customer:
                    path: customer
                    default: null
                    type: integer
        columns:
            orderId:
                label: 'ph.paymenthub.subscriptions.label.id'
                frontend_type: string
            total:
                label: 'ph.paymenthub.subscriptions.label.amount'
                frontend_type: string
            state:
                label: 'ph.paymenthub.subscriptions.label.state'
                frontend_type: string
            paymentState:
                label: 'ph.paymenthub.subscriptions.label.payment_state'
                frontend_type: string
            providerType:
                label: 'ph.paymenthub.subscriptions.label.method'
                frontend_type: string
            source:
                label: 'ph.paymenthub.subscriptions.label.source'
                frontend_type: string
            intention:
                label: 'ph.paymenthub.subscriptions.label.intention'
                frontend_type: string
            type:
                label: 'ph.paymenthub.subscriptions.label.type'
                frontend_type: string
            endDate:
                label: 'ph.paymenthub.subscriptions.label.end_date'
                frontend_type: date
            createdAt:
                label: 'ph.paymenthub.subscriptions.label.created_at'
                frontend_type: datetime
            updatedAt:
                label: 'ph.paymenthub.subscriptions.label.updated_at'
                frontend_type: datetime

        properties:
            id: ~
            update_link:
                type: url
                route: subscriptions.subscription_update
                params:
                    - id
            view_link:
                type: url
                route: subscriptions.subscription_view
                params:
                    - id
            delete_link:
                type: url
                route: subscriptions_api_delete_subscription
                params:
                    - id
        sorters:
            columns:
                state:
                    data_name: subscription.state
                createdAt:
                    data_name: subscription.createdAt
                updatedAt:
                    data_name: subscription.createdAt
                providerType:
                    data_name: subscription.providerType
            default:
                state: ASC
        filters:
            columns:
                state:
                    type: string
                    data_name: subscription.state
                createdAt:
                    type: datetime
                    data_name: subscription.createdAt
        actions:
            view:
                type:          navigate
                label:         View
                link:          view_link
                icon:          open
                acl_resource:  subscriptions.subscription_view
                rowAction:     true
            update:
                type:          navigate
                label:         Update
                link:          update_link
                icon:          edit
                acl_resource:  subscriptions.subscription_update
            delete:
                type:          delete
                label:         Delete
                link:          delete_link
                icon:          trash
                acl_resource:  subscriptions.subscription_delete


    ph-customer-notifications-grid:
        source:
            type: orm
            query:
                select:
                    - n.id
                    - n.type
                    - GROUP_CONCAT(customer.firstName, ' ', customer.lastName) AS customerFullName
                    - subscription.id AS subscriptionId
                    - n.sendAt
                from:
                    - { table: PHPaymentHubBundle:NotificationLog, alias: n }
                where:
                    and:
                        - n.customer = :customer
                join:
                    left:
                        - { join: n.customer, alias: customer }
                        - { join: n.subscription, alias: subscription }
            bind_parameters:
                customer:
                    path: customer
                    default: null
                    type: integer
        columns:
            id:
                label: 'Notification id'
                frontend_type: integer
            type:
                label: 'Notification type'
                frontend_type: string
            customerFullName:
                label: 'Customer'
            subscriptionId:
                label: 'Subscription id'
            sendAt:
                label: 'Created'
                frontend_type: datetime


        properties:
            id: ~
        sorters:
            columns:
                sendAt:
                    data_name: n.sendAt
            default:
                sendAt: DESC
