subscriptions_api_Subscription:
    resource:     "@PHPaymentHubBundle/Controller/Api/Rest/SubscriptionController.php"
    type:         rest
    prefix:       api/rest/{version}/ph/
    requirements:
        version:  latest|v1
        _format:  json
    defaults:
        version:  latest

subscriptions_api_Customer:
    resource:     "@PHPaymentHubBundle/Controller/Api/Rest/CustomerController.php"
    type:         rest
    prefix:       api/rest/{version}/ph/
    requirements:
        version:  latest|v1
        _format:  json
    defaults:
        version:  latest